/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandlordIndexRouteImport } from './routes/landlord.index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as LandlordIdRouteImport } from './routes/landlord.$id'

const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordIndexRoute = LandlordIndexRouteImport.update({
  id: '/landlord/',
  path: '/landlord/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordIdRoute = LandlordIdRouteImport.update({
  id: '/landlord/$id',
  path: '/landlord/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/landlord/$id': typeof LandlordIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/landlord/': typeof LandlordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/landlord/$id': typeof LandlordIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/landlord': typeof LandlordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/landlord/$id': typeof LandlordIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/landlord/': typeof LandlordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/login'
    | '/messages'
    | '/landlord/$id'
    | '/listing/$id'
    | '/landlord/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/browse'
    | '/login'
    | '/messages'
    | '/landlord/$id'
    | '/listing/$id'
    | '/landlord'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/login'
    | '/messages'
    | '/landlord/$id'
    | '/listing/$id'
    | '/landlord/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  LandlordIdRoute: typeof LandlordIdRoute
  ListingIdRoute: typeof ListingIdRoute
  LandlordIndexRoute: typeof LandlordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/': {
      id: '/landlord/'
      path: '/landlord'
      fullPath: '/landlord/'
      preLoaderRoute: typeof LandlordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/$id': {
      id: '/landlord/$id'
      path: '/landlord/$id'
      fullPath: '/landlord/$id'
      preLoaderRoute: typeof LandlordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  LandlordIdRoute: LandlordIdRoute,
  ListingIdRoute: ListingIdRoute,
  LandlordIndexRoute: LandlordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
